nelmio_cors:
    defaults:
        origin_regex: true
        allow_credentials: true
        allow_origin: ['*']
        allow_methods: ['GET', 'POST', 'PUT', 'OPTIONS']
        allow_headers: ['Content-Type', 'Authorization', 'X-API-KEY', 'Origin', 'X-Requested-With', 'Content-Type', 'Accept', 'Access-Control-Request-Method', 'Access-Control-Request-Headers', 'Authorization']
        expose_headers: ['Link']
        max_age: 3600
    paths:
        '^/': null
