<?php

define("GOOD_STATUS", 200);
define("UNAUTHORIZED_STATUS", 401);
define("FORBIDDEN_STATUS", 403);
define("NOT_FOUND_STATUS", 404);
define("METHOD_NOT_ALLOWED_STATUS", 405);
define("CONFLICT_STATUS", 409);
define("UNPROCESSABLE_ENTITY_STATUS", 422);
define("LOCKED_STATUS", 423);
