<?php

define("GOOD_STATUS_CODE", 200);
define("UNAUTHORIZED_STATUS_CODE", 401);
define("FORBIDDEN_STATUS_CODE", 403);
define("NOT_FOUND_STATUS_CODE", 404);
define("METHOD_NOT_ALLOWED_STATUS_CODE", 405);
define("CONFLICT_STATUS_CODE", 409);
define("GONE_STATUS_CODE", 410);
define("UNPROCESSABLE_ENTITY_STATUS_CODE", 422);
define("LOCKED_STATUS_CODE", 423);
